name = "unnamed-things-website"
main = "worker.js"
compatibility_date = "2024-01-01"

# This uploads all files in the current folder (HTML, CSS, Images)
[assets]
directory = "."
binding = "ASSETS"
{
  "d1_databases": [
    {
      "binding": "unnamed_db",
      "database_name": "unnamed-db",
      "database_id": "fe14d4bf-0853-4ec3-9546-130bdff1a63a"
    }
  ]
}