name = "unnamed-things-website"
main = "worker.js"
compatibility_date = "2024-01-01"

# This uploads all files in the current folder (HTML, CSS, Images)
[assets]
directory = "."
binding = "ASSETS"